- src/components/ListarVagasMonitor.jsx
- src/components/Notificacao.jsx
- src/pages/RegisterPage/index.jsx
Adionado atualizações nos dados de veículos
> :construction: feat: Adionado atualizações nos dados de veículos

- src/components/HistoricoVeiculo.jsx
- src/components/Sidebar.jsx
- src/pages/HomePage/index.jsx
Atualizações no histórico de veículos
> :construction: feat:Atualizações na consulta de veículos

- package-lock.json
- package.json
- src/components/BuscarVeiculo.jsx
- src/components/Camera.jsx
- src/components/Carregamento.jsx
- src/components/HistoricoVeiculo.jsx
- src/components/ListarNotificacoes.jsx
- src/components/ListarVagasMonitor.jsx
- src/components/Notificacao.jsx
- src/components/Register.jsx
- src/components/RegistrarEstacionamentoParceiro.jsx
- src/components/RegistrarVagaMonitor.jsx
- src/components/RegistrarVeiculo.jsx
> :bug: fix:Correção de bugs

- src/components/HistoricoFinanceiroParceiro.jsx
- src/components/ListarNotificacoes.jsx
- src/components/Register.jsx
- src/components/TransferenciaParceiro.jsx
- src/pages/Style/styles.css
Transferência crédito parceiro
> :construction: feat: Transferência crédito parceiro

- src/components/AdicionarCreditos.jsx
- src/components/BuscarVeiculo.jsx
- src/components/EstacionamentoAvulso.jsx
- src/components/HistoricoVeiculo.jsx
- src/components/InserirCreditos.jsx
- src/components/ListarVagasMonitor.jsx
- src/components/ListarVeiculos.jsx
- src/components/Notificacao.jsx
- src/components/RegistrarEstacionamentoParceiro.jsx
- src/components/RegistrarVagaCliente.jsx
- src/components/RegistrarVagaMonitor.jsx
- src/components/RegistrarVeiculo.jsx
- src/components/Regularizacao.jsx
- src/components/TransferirCreditoCliente.jsx
- src/util/ImpressaoTicketEstacionamento.jsx
- src/util/ImpressaoTicketNotificacao.jsx
Construção do sistema de impressão e correções
> :construction: feat: Construção do sistema de impressão e correções

- .env.development
- .env.production
- src/components/AbrirTurno.jsx
- src/components/AutoInfracao.jsx
- src/components/ClientesAdmin.jsx
- src/components/HistoricoFinanceiro.jsx
- src/components/HistoricoFinanceiroParceiro.jsx
- src/components/HistoricoVeiculo.jsx
- src/components/Irregularidades.jsx
- src/components/ListarNotificacoes.jsx
- src/components/ListarNotificacoesAgente.jsx
- src/components/ListarVagasMonitor.jsx
- src/components/ListarVeiculos.jsx
- src/components/LoginPage.jsx
- src/components/Notificacao.jsx
- src/components/OcupacaoVagasAdmin.jsx
- src/components/RegistrarVagaCliente.jsx
- src/components/RegistrarVagaMonitor.jsx
- src/components/SugestoesAdmin.jsx
- src/components/Suporte.jsx
- src/components/TransferirCreditoCliente.jsx
- src/components/UsuariosAdmin.jsx
- src/components/VeiculosAdmin.jsx
- src/util/Filtro.jsx
> :construction: feat: Criação da paginação

- src/components/AdicionarCreditos.jsx
- src/components/AutoInfracao.jsx
- src/components/ClientesAdmin.jsx
- src/components/Configuracoes.jsx
- src/components/ConfigurarPerfil.jsx
- src/components/Confirmation.jsx
- src/components/HistoricoVeiculo.jsx
- src/components/ListarNotificacoes.jsx
- src/components/ListarVagasMonitor.jsx
- src/components/ListarVeiculos.jsx
- src/components/LoginPage.jsx
- src/components/NewPassword.jsx
- src/components/Register.jsx
- src/components/RegistrarEstacionamentoParceiro.jsx
- src/components/RegistrarVagaCliente.jsx
- src/components/ResetPassword.jsx
- src/components/SetoresAdmin.jsx
- src/components/Sidebar.jsx
- src/util/ImpressaoTicketEstacionamento.jsx
:bug: fix: Correções de bugs por todo o sistema
> :bug: fix: Correções de bugs por todo o sistema

- .env.development
- .env.production
- src/components/BuscarVeiculo.jsx
- src/components/Camera.jsx
- src/components/CameraTicketNotificacao.jsx
- src/components/ListarVagasMonitor.jsx
- src/components/Notificacao.jsx
- src/util/ImpressaoTicketEstacionamento.jsx
:construction: implementações pedidas pelas monitoras
> :construction: implementações pedidas pelas monitoras

- .env.development
- .env.production
- src/components/Camera.jsx
- src/components/CameraAutoInfracao.jsx
- src/components/CameraTicketNotificacao.jsx
- src/components/ListarNotificacoes.jsx
- src/components/Sidebar.jsx
- src/components/SugestoesAdmin.jsx
- src/components/Suporte.jsx
> :bug: fix: Correções de bugs

- src/components/Suporte.jsx
:construction: feat: implementações de vídeos para auxiliar o usuario
> :construction: feat: implementações de vídeos para auxiliar o usuario

- src/components/AbrirTurno.jsx
- src/components/ListarNotificacoesAdmin.jsx
- src/components/RegistrarEstacionamentoParceiro.jsx
- src/components/RegistrarVagaMonitor.jsx
:bug: fix: Corrigido o bug do tempo errado no ticket
> :bug: fix: Corrigido o bug do tempo errado no ticket

- .env.development
- .env.production
- src/components/ListarVagasMonitor.jsx
:bug: fix: Corrigido não descer para a vaga selecionada
> :bug: fix: Corrigido não descer para a vaga selecionada

- src/components/RegistrarVagaMonitor.jsx
:bug: fix: Correção de bug placa vazia notificação
> :bug: fix: Correção de bug placa vazia notificação

- src/components/Irregularidades.jsx
- src/components/ListarVagasMonitor.jsx
- src/components/ListarVeiculos.jsx
- src/components/RegistrarVagaCliente.jsx
- src/components/RegistrarVagaMonitor.jsx
- src/components/Sidebar.jsx
- src/components/Suporte.jsx
:bug: fix: Arrumada questao de notificacao bugada
> :bug: fix: Arrumada questao de notificacao bugada

- src/components/ListarNotificacoes.jsx
- src/components/ListarVeiculos.jsx
Co-authored-by: WendelGustavo wendelgfillmann@gmail.com
> :bug: fix:Correcoes de bugs listar veiculos cliente

- src/components/PrestacaoContas.jsx
:bug: fix: Corrigido a formatação dos numero no prestacao de contas
> :bug: fix: Corrigido a formatação dos numero no prestacao de contas

- src/components/ListarVeiculos.jsx
- src/util/EnviarNotificacao.jsx
- src/util/LimparNotificacao.jsx
:construction: feat: Push de notificacao
> :construction: feat: Push de notificacao

- src/components/Configuracoes.jsx
- src/components/InserirCreditos.jsx
- src/components/ListarVeiculos.jsx
- src/components/Suporte.jsx
- src/pages/Style/styles.css
:bug: fix: Correções de layout
> :bug: fix: Correções de layout

- src/components/InserirCreditos.jsx
- src/components/PrestacaoContas.jsx
- src/util/Filtro.jsx
:bug: fix:Correções no filtro e nos valores do prestação de contas
> :bug: fix:Correções no filtro e nos valores do prestação de contas

- src/components/ListarVeiculos.jsx
:construction: feat: Comprovante de estacionamento
> :construction: feat: Comprovante de estacionamento

- src/components/ListarVagasMonitor.jsx
- src/components/RegistrarVagaMonitor.jsx
:bug: fix: Corrido bug de não conseguir subir no listar vagas
> :bug: fix: Corrido bug de não conseguir subir no listar vagas

- src/components/ListarVeiculos.jsx
:bug: fix: Correção de bug do valor maior que mil
> :bug: fix: Correção de bug do valor maior que mil

- src/components/CartaoCredito.jsx
- src/components/InserirCreditos.jsx
:bug: fix: Correção de voltar para o componente com o 'PIX' selecionado
> :bug: fix: Correção de voltar para o componente com o 'PIX' selecionado
